AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  html-to-pdf-api

  Sample SAM Template for html-to-pdf-api

Globals:
  Function:
    Timeout: 3

Resources:
  HtmlToPdfFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /html-to-pdf
            Method: get
